### ISSUE TITLE
How to enable OPENCV_ENABLE_NONFREE for usage of SURF

### ISSUE THREAD

**Issue by ryanperezx** [iamareebjamal/opencv-android#13]
Hi, I'm doing a project for my major subject which uses the SURF Algorithm.  I'm getting the error

E/cv::error(): OpenCV(4.1.2) Error: The function/feature is not implemented (This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library) in create, file /build/master-contrib_pack-contrib-android/opencv_contrib/modules/xfeatures2d/src/surf.cpp, line 1029

Do I really have to build the library (w/ contrib) from CMake?

**Comment by a1inani** [comment]
I have a similar issue but with SIFT. Is it possible that a build could be provided with the OPENCV_ENABLE_NONFREE CMake option set?
