### ISSUE TITLE
 No implementation found 

### ISSUE THREAD

**Issue by muratdoglu** [iamareebjamal/opencv-android#14]
hi, an error like this

`No implementation found for void org.opencv.xphoto.Xphoto.inpaint_0(long, long, long, int) (tried Java_org_opencv_xphoto_Xphoto_inpaint_10 and Java_org_opencv_xphoto_Xphoto_inpaint_10__JJJI)`

**Comment by muratdoglu** [comment]
@iamareebjamal

**Comment by iamareebjamal** [comment]
Are you sure you are using the contrib module?

**Comment by muratdoglu** [comment]
is it enought?  @iamareebjamal 
<img width="542" alt="Screen Shot 2020-03-10 at 3 10 41 PM" src="https://user-images.githubusercontent.com/19818531/76311170-6632f280-62e1-11ea-8325-b7ef86efac34.png">

**Comment by iamareebjamal** [comment]
Should be. Unless it requires another module to be compiled

**Comment by muratdoglu** [comment]
This error does not come when switching to the 4.1.2 module. there is only 4.2.0

**Comment by iamareebjamal** [comment]
Will check what's the issue

**Comment by muratdoglu** [comment]
I think it doesn't find native lib files. If you can send me the lib files, I can add it manually and tell the result of the problem.

**Comment by iamareebjamal** [comment]
It gets automatically downloaded from OpenCV https://github.com/iamareebjamal/opencv-android/blob/contrib/setup_opencv.sh and built

https://github.com/iamareebjamal/opencv-android/blob/beff48e710d3b159452e8b5ef7855c292b80d0f3/.circleci/config.yml#L11-L21

**Comment by muratdoglu** [comment]
@iamareebjamal  
I tried this. I get the libc++_ shared.so file not found error. Do you have any idea about this topic?

**Comment by muratdoglu** [comment]
<img width="1133" alt="Screen Shot 2020-03-10 at 4 24 55 PM" src="https://user-images.githubusercontent.com/19818531/76316528-cd55a480-62eb-11ea-8255-384d9906ef6d.png">

**Comment by muratdoglu** [comment]
I created my project from the beginning, I tried it, thank you.

**Comment by iamareebjamal** [comment]
Did you solve your problem?

**Comment by iamareebjamal** [comment]
Closing the issue. If you are still having problem, I'll be happy to help
